name: ci-golang-workflow
on: 
  pull_request:
    branches:
     - develop
     
jobs:
  check-application:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.14', '1.13' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go run math.go
